Repository parallaxsecond/parsec, pull requests merged in 2020-02, with the labels that each got.

#99 Add cargo clippy lints to the CI
  Cargo.lock
  Cargo.toml
  build.rs
  src/bin/main.rs
  src/lib.rs
  tests/ci.sh
  tests/mod.rs
  tests/per_provider/normal_tests/export_public_key.rs
  tests/per_provider/provider_cfg/mbed-crypto/Dockerfile
Labels: enhancement

#101 Review ResponseStatus usage
  Cargo.lock
  Cargo.toml
  src/key_id_managers/mod.rs
  src/providers/mbed_provider/mod.rs
  src/providers/mbed_provider/utils.rs
  src/providers/mod.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/pkcs11_provider/utils.rs
  src/providers/tpm_provider/mod.rs
  src/providers/tpm_provider/utils.rs
  tests/per_provider/normal_tests/asym_sign_verify.rs
  tests/per_provider/normal_tests/auth.rs
  tests/per_provider/normal_tests/basic.rs
  tests/per_provider/normal_tests/create_destroy_key.rs
  tests/per_provider/normal_tests/export_public_key.rs
  tests/per_provider/normal_tests/import_key.rs
  tests/per_provider/persistent_after.rs
Labels: bug, invalid

#104 Add owner hierarchy auth param
  config.toml
  src/providers/mod.rs
  src/providers/tpm_provider/mod.rs
  src/utils/service_builder.rs
  tests/all_providers/config.toml
  tests/ci.sh
  tests/per_provider/provider_cfg/tpm/config.toml
Labels: bug

#109 Prepare for upload to crates io
  Cargo.lock
  Cargo.toml
  src/bin/main.rs
  tests/ci.sh
Labels: enhancement

#110 Fix the handling of versioning
  Cargo.lock
  Cargo.toml
  README.md
  src/back/backend_handler.rs
  src/providers/core_provider/mod.rs
  src/providers/mbed_provider/mod.rs
  src/providers/mod.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/mod.rs
  src/utils/service_builder.rs
  tests/ci.sh
  tests/per_provider/normal_tests/basic.rs
Labels: invalid

#111 Rename the simple authenticator as direct
  Cargo.lock
  Cargo.toml
  src/authenticators/direct_authenticator/mod.rs
  src/authenticators/mod.rs
  src/utils/service_builder.rs
  tests/per_provider/normal_tests/ping.rs
Labels: invalid

#114 Modify configuration to have provider-specific structs
  src/providers/mod.rs
  src/utils/service_builder.rs
Labels: enhancement

#113 Improve code documentation
  Cargo.lock
  Cargo.toml
  src/authenticators/direct_authenticator/mod.rs
  src/authenticators/mod.rs
  src/back/backend_handler.rs
  src/back/dispatcher.rs
  src/back/mod.rs
  src/front/domain_socket.rs
  src/front/front_end.rs
  src/front/listener.rs
  src/front/mod.rs
  src/key_id_managers/mod.rs
  src/key_id_managers/on_disk_manager/mod.rs
  src/lib.rs
  src/providers/core_provider/mod.rs
  src/providers/mod.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/mod.rs
  src/utils/mod.rs
  src/utils/service_builder.rs
Labels: enhancement

#115 Bump version and add Anton as maintainer
  Cargo.lock
  Cargo.toml
  MAINTAINERS.toml
Labels: invalid
