Repository parallaxsecond/parsec, pull requests merged in 2020-10, with the labels that each got.

#257 Modify socket path to conform to FHS
  Cargo.toml
  ci.sh
  config.toml
  e2e_tests/Cargo.toml
  e2e_tests/provider_cfg/all/config.toml
  e2e_tests/provider_cfg/mbed-crypto/config.toml
  e2e_tests/provider_cfg/pkcs11/config.toml
  e2e_tests/provider_cfg/tpm/config.toml
  e2e_tests/src/lib.rs
  e2e_tests/src/raw_request.rs
  e2e_tests/tests/config/tomls/list_providers_1.toml
  e2e_tests/tests/config/tomls/list_providers_2.toml
  e2e_tests/tests/config/tomls/pkcs11_software.toml
  e2e_tests/tests/per_provider/normal_tests/export_key.rs
  e2e_tests/tests/per_provider/normal_tests/ping.rs
  fuzz/config.toml
  src/front/domain_socket.rs
  src/front/front_end.rs
  src/front/listener.rs
  src/key_info_managers/on_disk_manager/mod.rs
  src/utils/service_builder.rs
  systemd-daemon/parsec.service
Labels: invalid

#259 Remove disclaimer
  .github/workflows/ci.yml
  README.md
Labels: invalid

#255 Limit key imports in TPM provider
  src/providers/tpm_provider/key_management.rs
Labels: bug

#260 Improve error message on service startup
  Cargo.lock
  Cargo.toml
  src/bin/main.rs
  src/front/domain_socket.rs
  src/key_info_managers/on_disk_manager/mod.rs
  src/utils/service_builder.rs
Labels: enhancement

#273 Add authentication configuration
  Cargo.lock
  config.toml
  e2e_tests/provider_cfg/all/config.toml
  e2e_tests/provider_cfg/mbed-crypto/config.toml
  e2e_tests/provider_cfg/pkcs11/config.toml
  e2e_tests/provider_cfg/tpm/config.toml
  e2e_tests/tests/config/tomls/list_providers_1.toml
  e2e_tests/tests/config/tomls/list_providers_2.toml
  e2e_tests/tests/config/tomls/pkcs11_software.toml
  fuzz/config.toml
  src/authenticators/mod.rs
  src/utils/service_builder.rs
Labels: multitenancy

#276 Add multitenancy tests
  Cargo.lock
  Cargo.toml
  ci.sh
  e2e_tests/Cargo.toml
  e2e_tests/provider_cfg/all/Dockerfile
  e2e_tests/src/lib.rs
  e2e_tests/src/stress.rs
  e2e_tests/tests/all_providers/mod.rs
  e2e_tests/tests/all_providers/multitenancy.rs
  e2e_tests/tests/all_providers/normal.rs
  e2e_tests/tests/per_provider/normal_tests/auth.rs
  e2e_tests/tests/per_provider/normal_tests/key_attributes.rs
  e2e_tests/tests/per_provider/persistent_after.rs
Labels: multitenancy

#277 Remove PKCS11 single thread lock (#264)
  e2e_tests/provider_cfg/all/Dockerfile
  e2e_tests/provider_cfg/pkcs11/Dockerfile
  e2e_tests/src/stress.rs
  src/providers/pkcs11/mod.rs
Labels: enhancement

#280 Add Changelog file (#278)
  CHANGELOG.md
Labels: enhancement
