Repository parallaxsecond/parsec, pull requests merged in 2020-08, with the labels that each got.

#225 Add asymmetric encryption support to TPM provider
  Cargo.lock
  Cargo.toml
  e2e_tests/Cargo.toml
  e2e_tests/src/lib.rs
  e2e_tests/tests/all_providers/mod.rs
  e2e_tests/tests/per_provider/normal_tests/asym_encryption.rs
  e2e_tests/tests/per_provider/normal_tests/asym_sign_verify.rs
  src/providers/tpm_provider/asym_encryption.rs
  src/providers/tpm_provider/mod.rs
  src/providers/tpm_provider/utils.rs
  tests/providers/tpm.rs
Labels: enhancement

#234 Bugfix: fix off-by-one error (default body length limit)
  src/utils/service_builder.rs
Labels: bug

#237 Rename Mbed" to MbedCrypto
  Cargo.toml
  ci.sh
  fuzz/config.toml
  src/providers/mbed_crypto_provider/aead.rs
  src/providers/mbed_crypto_provider/asym_encryption.rs
  src/providers/mbed_crypto_provider/asym_sign.rs
  src/providers/mbed_crypto_provider/hash.rs
  src/providers/mbed_crypto_provider/key_agreement.rs
  src/providers/mbed_crypto_provider/key_management.rs
  src/providers/mbed_crypto_provider/mod.rs
  src/providers/mod.rs
  src/utils/service_builder.rs
Labels: enhancement, invalid
