Repository parallaxsecond/parsec, pull requests merged in 2020-01, with the labels that each got.

#85 Switch crates to use picky-asn1-der
  Cargo.lock
  Cargo.toml
  README.md
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/mod.rs
Labels: enhancement

#82 Allow optional providers and key ID managers
  src/utils/service_builder.rs
Labels: enhancement

#86 Add sign to ASN.1 Integer types for RSAPublicKey
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/mod.rs
Labels: bug

#87 Deny compilation for some rustc lints
  Cargo.lock
  Cargo.toml
  README.md
  src/authenticators/simple_authenticator/mod.rs
  src/back/backend_handler.rs
  src/back/dispatcher.rs
  src/bin/main.rs
  src/front/domain_socket.rs
  src/front/front_end.rs
  src/front/listener.rs
  src/key_id_managers/mod.rs
  src/key_id_managers/on_disk_manager/mod.rs
  src/lib.rs
  src/providers/core_provider/mod.rs
  src/providers/mbed_provider/mod.rs
  src/providers/mbed_provider/utils.rs
  src/providers/mod.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/mod.rs
  src/utils/service_builder.rs
Labels: enhancement

#88 Add a verify-only integration test
  Cargo.lock
  Cargo.toml
  src/key_id_managers/on_disk_manager/mod.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/mod.rs
  src/utils/service_builder.rs
  tests/all_providers/ci.sh
  tests/all_providers/mod.rs
  tests/per_provider/ci.sh
  tests/per_provider/normal_tests/asym_sign_verify.rs
  tests/per_provider/normal_tests/auth.rs
  tests/per_provider/normal_tests/basic.rs
  tests/per_provider/normal_tests/create_destroy_key.rs
  tests/per_provider/normal_tests/export_public_key.rs
  tests/per_provider/normal_tests/import_key.rs
  tests/per_provider/normal_tests/ping.rs
  tests/per_provider/persistent_after.rs
  tests/per_provider/persistent_before.rs
  tests/per_provider/stress_test.rs
Labels: bug

#90 Modify Travis CI test script
  .cargo/config
  .github/workflows/ci.yml
  .travis.yml
  Cross.toml
  README.md
  tests/all_providers/ci.sh
  tests/all_providers/config.toml
  tests/ci.sh
  tests/cross_compilation/Dockerfile
  tests/per_provider/ci.sh
  tests/per_provider/provider_cfg/mbed-crypto/Dockerfile
  tests/per_provider/provider_cfg/mbed-crypto/config.toml
  tests/per_provider/provider_cfg/pkcs11/Dockerfile
  tests/per_provider/provider_cfg/pkcs11/config.toml
  tests/per_provider/provider_cfg/tpm/config.toml
Labels: enhancement

#92 Replace most panicking behaviours with Result
  Cargo.lock
  Cargo.toml
  build.rs
  src/back/backend_handler.rs
  src/back/dispatcher.rs
  src/bin/main.rs
  src/front/domain_socket.rs
  src/front/front_end.rs
  src/key_id_managers/on_disk_manager/mod.rs
  src/providers/core_provider/mod.rs
  src/providers/mbed_provider/mod.rs
  src/providers/mbed_provider/utils.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/mod.rs
  src/utils/service_builder.rs
Labels: enhancement

#93 Ensure the safety of unsafe blocks
  src/providers/mbed_provider/mod.rs
  src/providers/mbed_provider/utils.rs
  tests/all_providers/config.toml
  tests/ci.sh
  tests/per_provider/provider_cfg/mbed-crypto/config.toml
  tests/per_provider/provider_cfg/pkcs11/config.toml
  tests/per_provider/provider_cfg/tpm/config.toml
Labels: enhancement

#96 Add body length limit
  Cargo.lock
  Cargo.toml
  config.toml
  src/front/front_end.rs
  src/utils/service_builder.rs
Labels: bug, enhancement
