Repository parallaxsecond/parsec, pull requests merged in 2020-06, with the labels that each got.

#178 Import the newest Parsec interface
  Cargo.lock
  Cargo.toml
  ci.sh
  e2e_tests/Cargo.toml
  e2e_tests/src/lib.rs
  e2e_tests/tests/per_provider/normal_tests/asym_sign_verify.rs
  e2e_tests/tests/per_provider/normal_tests/create_destroy_key.rs
  e2e_tests/tests/per_provider/normal_tests/export_public_key.rs
  e2e_tests/tests/per_provider/normal_tests/import_key.rs
  e2e_tests/tests/per_provider/normal_tests/key_attributes.rs
  src/key_info_managers/mod.rs
  src/key_info_managers/on_disk_manager/mod.rs
  src/providers/mbed_provider/key_management.rs
  src/providers/mbed_provider/utils.rs
  src/providers/pkcs11_provider/asym_sign.rs
  src/providers/pkcs11_provider/key_management.rs
  src/providers/tpm_provider/key_management.rs
  src/providers/tpm_provider/utils.rs
  tests/providers/tpm.rs
Labels: enhancement

#179 Use crates.io version of the interface
  Cargo.lock
  Cargo.toml
  src/providers/mbed_provider/asym_sign.rs
  src/providers/mbed_provider/key_management.rs
  src/providers/mbed_provider/utils.rs
Labels: enhancement

#180 Add community repo link
  README.md
  tests/providers/tpm.rs
Labels: enhancement

#185 Add trace logging on Provide method calls
  src/back/backend_handler.rs
  src/back/dispatcher.rs
  src/bin/main.rs
  src/front/front_end.rs
  src/providers/core_provider/mod.rs
  src/providers/mbed_provider/mod.rs
  src/providers/mod.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/mod.rs
Labels: enhancement

#183 Improve log security
  src/front/domain_socket.rs
  src/front/front_end.rs
  src/key_info_managers/mod.rs
  src/key_info_managers/on_disk_manager/mod.rs
  src/providers/core_provider/mod.rs
  src/providers/pkcs11_provider/asym_sign.rs
  src/providers/pkcs11_provider/key_management.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/pkcs11_provider/utils.rs
  src/providers/tpm_provider/asym_sign.rs
  src/providers/tpm_provider/key_management.rs
  src/providers/tpm_provider/mod.rs
  src/providers/tpm_provider/utils.rs
  src/utils/service_builder.rs
Labels: Security, enhancement

#184 Update fuzz target
  fuzz.sh
  fuzz/.gitignore
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  fuzz/build.rs
  fuzz/config.toml
  fuzz/docker/Dockerfile
  fuzz/fuzz_targets/fuzz_service.rs
  fuzz/init_corpus/example-create-key
  fuzz/init_corpus/example-destroy-key
  fuzz/init_corpus/example-export-public-key
  fuzz/init_corpus/example-import-key
  fuzz/init_corpus/example-ping
  fuzz/init_corpus/example-sign
  fuzz/init_corpus/example-verify
  fuzz/run_fuzz.sh
Labels: enhancement

#188 Fixed PKCS#11 provieder failing failed_created_key_should_be_removed test
  src/providers/pkcs11_provider/key_management.rs
Labels: bug

#189 Implement mitigation 4 of TM
  src/front/front_end.rs
  src/key_info_managers/on_disk_manager/mod.rs
  src/providers/pkcs11_provider/asym_sign.rs
  src/providers/pkcs11_provider/key_management.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/pkcs11_provider/utils.rs
Labels: security

#190 Removed duplicate macros for sign output size and export pub key size.
  Cargo.toml
  src/providers/mbed_provider/asym_sign.rs
  src/providers/mbed_provider/key_management.rs
  src/providers/mbed_provider/mod.rs
  src/providers/mbed_provider/utils.rs
Labels: enhancement

#191 Changed local_ids for Atomic counter and removed key_slot_semaphore.
  src/providers/mbed_provider/asym_sign.rs
  src/providers/mbed_provider/key_management.rs
  src/providers/mbed_provider/mod.rs
Labels: enhancement
