Repository parallaxsecond/parsec, pull requests merged in 2020-07, with the labels that each got.

#193 Updated Parsec to use latest parsec-interface (0.17.0)
  Cargo.toml
  src/authenticators/direct_authenticator/mod.rs
  src/providers/mbed_provider/asym_sign.rs
  src/providers/mbed_provider/key_management.rs
  src/providers/pkcs11_provider/asym_sign.rs
  src/providers/pkcs11_provider/key_management.rs
  src/providers/tpm_provider/asym_sign.rs
  src/providers/tpm_provider/key_management.rs
  src/providers/tpm_provider/utils.rs
  tests/providers/tpm.rs
Labels: enhancement

#192 Modify socket path
  Cargo.lock
  e2e_tests/src/lib.rs
  e2e_tests/src/raw_request.rs
  e2e_tests/tests/per_provider/normal_tests/create_destroy_key.rs
  e2e_tests/tests/per_provider/normal_tests/ping.rs
  src/front/domain_socket.rs
  systemd-daemon/parsec.service
  systemd-daemon/parsec.socket
Labels: enhancement, security

#194 Add TCTI configuration functionality
  Cargo.lock
  Cargo.toml
  config.toml
  e2e_tests/provider_cfg/tpm/config.toml
  src/providers/tpm_provider/mod.rs
Labels: enhancement

#203 Precise the providers' order importance
  config.toml
Labels: enhancement

#206 Fix clippy errors
  e2e_tests/tests/per_provider/normal_tests/asym_encryption.rs
  src/bin/main.rs
  src/key_info_managers/on_disk_manager/mod.rs
  src/providers/core_provider/mod.rs
  src/providers/mbed_provider/key_management.rs
  src/providers/pkcs11_provider/key_management.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/asym_sign.rs
  src/providers/tpm_provider/key_management.rs
  src/providers/tpm_provider/mod.rs
  src/providers/tpm_provider/utils.rs
  src/utils/service_builder.rs
Labels: bug

#211 Improve error message when config file is not found
  src/bin/main.rs
Labels: enhancement
