Repository parallaxsecond/parsec, pull requests merged in 2020-09, with the labels that each got.

#235 Update email address
  MAINTAINERS.toml
Labels: bug

#233 Add `buffer_size_limit` config option for providers
  config.toml
  src/utils/global_config.rs
  src/utils/service_builder.rs
Labels: bug

#239 Add memory zeroizing when needed
  src/key_info_managers/mod.rs
  src/providers/mod.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/pkcs11_provider/utils.rs
  src/providers/tpm_provider/key_management.rs
  src/providers/tpm_provider/mod.rs
  src/providers/tpm_provider/utils.rs
Labels: security

#240 Improve key metadata handling
  src/key_info_managers/mod.rs
  src/providers/mbed_crypto_provider/mod.rs
  src/providers/pkcs11_provider/asym_encryption.rs
  src/providers/pkcs11_provider/asym_sign.rs
  src/providers/pkcs11_provider/key_management.rs
  src/providers/pkcs11_provider/key_metadata.rs
  src/providers/pkcs11_provider/mod.rs
Labels: enhancement

#242 Add Uuid from the interface directly
  e2e_tests/Cargo.toml
  e2e_tests/tests/all_providers/mod.rs
  e2e_tests/tests/config/mod.rs
Labels: bug

#208 Add support for `psa_generate_random` operation for MbedCrypto provider
  e2e_tests/src/lib.rs
  e2e_tests/tests/all_providers/mod.rs
  e2e_tests/tests/per_provider/normal_tests/generate_random.rs
  e2e_tests/tests/per_provider/normal_tests/mod.rs
  src/back/backend_handler.rs
  src/providers/mbed_crypto_provider/generate_random.rs
  src/providers/mbed_crypto_provider/mod.rs
  src/providers/mod.rs
Labels: enhancement

#243 Import private key support for TPM provider
  Cargo.lock
  Cargo.toml
  src/providers/pkcs11_provider/key_management.rs
  src/providers/tpm_provider/key_management.rs
  src/providers/tpm_provider/mod.rs
  src/providers/tpm_provider/utils.rs
  tests/providers/tpm.rs
Labels: enhancement

#246 Upgrade and clean dependencies
  .github/workflows/nightly.yml
  Cargo.lock
  Cargo.toml
  README.md
  e2e_tests/Cargo.toml
  e2e_tests/provider_cfg/mbed-crypto/Dockerfile
  e2e_tests/tests/per_provider/normal_tests/aead.rs
  e2e_tests/tests/per_provider/normal_tests/import_key.rs
  e2e_tests/tests/per_provider/normal_tests/key_agreement.rs
  src/providers/pkcs11_provider/key_management.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/pkcs11_provider/utils.rs
Labels: enhancement

#252 Fix sign attribute in PKCS11
  src/providers/pkcs11_provider/utils.rs
Labels: bug

#253 Improve E2E testing
  Cargo.lock
  Cargo.toml
  e2e_tests/Cargo.toml
  e2e_tests/src/lib.rs
  e2e_tests/src/stress.rs
  e2e_tests/tests/all_providers/cross.rs
  e2e_tests/tests/all_providers/mod.rs
  e2e_tests/tests/per_provider/normal_tests/aead.rs
  e2e_tests/tests/per_provider/normal_tests/asym_encryption.rs
  e2e_tests/tests/per_provider/normal_tests/asym_sign_verify.rs
  e2e_tests/tests/per_provider/normal_tests/basic.rs
  e2e_tests/tests/per_provider/normal_tests/export_key.rs
  e2e_tests/tests/per_provider/normal_tests/generate_random.rs
  e2e_tests/tests/per_provider/normal_tests/hash.rs
  e2e_tests/tests/per_provider/normal_tests/import_key.rs
  e2e_tests/tests/per_provider/normal_tests/key_agreement.rs
  tests/mod.rs
  tests/providers/mod.rs
  tests/providers/tpm.rs
Labels: bug, enhancement

#254 Fix attribute conversion in PKCS11 provider
  src/providers/pkcs11_provider/utils.rs
Labels: bug
