Repository parallaxsecond/parsec, pull requests merged in 2020-04, with the labels that each got.

#138 Add KeyInfo to the KeyIDManager
  Cargo.lock
  Cargo.toml
  src/key_id_managers/mod.rs
  src/key_id_managers/on_disk_manager/mod.rs
  src/providers/mbed_provider/mod.rs
  src/providers/mbed_provider/utils.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/mod.rs
  tests/ci.sh
  tests/per_provider/normal_tests/key_attributes.rs
Labels: invalid

#142 Modify error translation coming from providers
  src/providers/pkcs11_provider/mod.rs
  src/providers/pkcs11_provider/utils.rs
  src/providers/tpm_provider/mod.rs
  src/providers/tpm_provider/utils.rs
Labels: invalid

#145 Remove stress test on Travis CI for PKCS 11
  .travis.yml
  tests/ci.sh
  tests/per_provider/provider_cfg/mbed-crypto/config.toml
  tests/per_provider/provider_cfg/pkcs11/config.toml
  tests/per_provider/provider_cfg/tpm/config.toml
Labels: enhancement

#144 Add tests for operations edge cases
  Cargo.lock
  Cargo.toml
  README.md
  src/providers/mbed_provider/mod.rs
  src/providers/mbed_provider/utils.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/mod.rs
  tests/all_providers/mod.rs
  tests/per_provider/normal_tests/asym_sign_verify.rs
  tests/per_provider/normal_tests/create_destroy_key.rs
  tests/per_provider/normal_tests/export_public_key.rs
  tests/per_provider/normal_tests/import_key.rs
  tests/per_provider/normal_tests/key_attributes.rs
Labels: invalid

#150 Move test client back in the Parsec repo
  Cargo.lock
  Cargo.toml
  README.md
  tests/all_providers/mod.rs
  tests/mod.rs
  tests/per_provider/normal_tests/asym_sign_verify.rs
  tests/per_provider/normal_tests/auth.rs
  tests/per_provider/normal_tests/basic.rs
  tests/per_provider/normal_tests/create_destroy_key.rs
  tests/per_provider/normal_tests/export_public_key.rs
  tests/per_provider/normal_tests/import_key.rs
  tests/per_provider/normal_tests/key_attributes.rs
  tests/per_provider/normal_tests/ping.rs
  tests/per_provider/persistent_after.rs
  tests/per_provider/persistent_before.rs
  tests/per_provider/stress_test.rs
  tests/test_clients/mod.rs
  tests/test_clients/raw_request.rs
  tests/test_clients/stress.rs
Labels: enhancement

#157 Fix clippy errors
  Cargo.lock
  Cargo.toml
  src/utils/service_builder.rs
  tests/per_provider/provider_cfg/mbed-crypto/Dockerfile
  tests/per_provider/provider_cfg/pkcs11/Dockerfile
Labels: bug

#154 Allow PKCS11 tests to fail on Travis
  .travis.yml
Labels: bug

#156 Update copyrights
  CONTRIBUTING.md
  Cargo.lock
  DCO.txt
  PARTNERS.md
  README.md
  build.rs
  fuzz.sh
  fuzz/cleanup.sh
  fuzz/fuzz_targets/fuzz_service.rs
  fuzz/run_fuzz.sh
  setup_mbed_crypto.sh
  src/authenticators/direct_authenticator/mod.rs
  src/authenticators/mod.rs
  src/back/backend_handler.rs
  src/back/dispatcher.rs
  src/back/mod.rs
  src/bin/main.rs
  src/front/domain_socket.rs
  src/front/front_end.rs
  src/front/listener.rs
  src/front/mod.rs
  src/key_id_managers/mod.rs
  src/key_id_managers/on_disk_manager/mod.rs
  src/lib.rs
  src/providers/core_provider/mod.rs
  src/providers/mbed_provider/constants.rs
  src/providers/mbed_provider/mod.rs
  src/providers/mbed_provider/utils.rs
  src/providers/mod.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/pkcs11_provider/utils.rs
  src/providers/tpm_provider/mod.rs
  src/providers/tpm_provider/utils.rs
  src/utils/mod.rs
  src/utils/service_builder.rs
  tests/all_providers/mod.rs
  tests/ci.sh
  tests/mod.rs
  tests/per_provider/mod.rs
  tests/per_provider/normal_tests/asym_sign_verify.rs
  tests/per_provider/normal_tests/auth.rs
  tests/per_provider/normal_tests/basic.rs
  tests/per_provider/normal_tests/create_destroy_key.rs
  tests/per_provider/normal_tests/export_public_key.rs
  tests/per_provider/normal_tests/import_key.rs
  tests/per_provider/normal_tests/key_attributes.rs
  tests/per_provider/normal_tests/mod.rs
  tests/per_provider/normal_tests/ping.rs
  tests/per_provider/persistent_after.rs
  tests/per_provider/persistent_before.rs
  tests/per_provider/provider_cfg/pkcs11/find_slot_number.sh
  tests/per_provider/stress_test.rs
Labels: invalid

#152 Rename key ID to key info
  Cargo.lock
  Cargo.toml
  config.toml
  fuzz/config.toml
  src/key_info_managers/mod.rs
  src/key_info_managers/on_disk_manager/mod.rs
  src/lib.rs
  src/providers/mbed_provider/mod.rs
  src/providers/mod.rs
  src/providers/pkcs11_provider/mod.rs
  src/providers/tpm_provider/mod.rs
  src/utils/service_builder.rs
  tests/all_providers/config.toml
  tests/ci.sh
  tests/per_provider/normal_tests/basic.rs
  tests/per_provider/provider_cfg/mbed-crypto/config.toml
  tests/per_provider/provider_cfg/pkcs11/config.toml
  tests/per_provider/provider_cfg/tpm/config.toml
Labels: invalid

#160 Move end to end tests to own crate
  .github/workflows/ci.yml
  .travis.yml
  e2e_tests/.gitignore
  e2e_tests/Cargo.toml
  e2e_tests/provider_cfg/all/Dockerfile
  e2e_tests/provider_cfg/all/config.toml
  e2e_tests/provider_cfg/mbed-crypto/Dockerfile
  e2e_tests/provider_cfg/mbed-crypto/config.toml
  e2e_tests/provider_cfg/pkcs11/Dockerfile
  e2e_tests/provider_cfg/pkcs11/config.toml
  e2e_tests/provider_cfg/pkcs11/find_slot_number.sh
  e2e_tests/provider_cfg/tpm/Dockerfile
  e2e_tests/provider_cfg/tpm/config.toml
  e2e_tests/src/lib.rs
  e2e_tests/src/raw_request.rs
  e2e_tests/src/stress.rs
  e2e_tests/tests/all_providers/mod.rs
  e2e_tests/tests/mod.rs
  e2e_tests/tests/per_provider/mod.rs
  e2e_tests/tests/per_provider/normal_tests/asym_sign_verify.rs
  e2e_tests/tests/per_provider/normal_tests/auth.rs
  e2e_tests/tests/per_provider/normal_tests/basic.rs
  e2e_tests/tests/per_provider/normal_tests/create_destroy_key.rs
  e2e_tests/tests/per_provider/normal_tests/export_public_key.rs
  e2e_tests/tests/per_provider/normal_tests/import_key.rs
  e2e_tests/tests/per_provider/normal_tests/key_attributes.rs
  e2e_tests/tests/per_provider/normal_tests/mod.rs
  e2e_tests/tests/per_provider/normal_tests/ping.rs
  e2e_tests/tests/per_provider/persistent_after.rs
  e2e_tests/tests/per_provider/persistent_before.rs
  e2e_tests/tests/per_provider/stress_test.rs
  tests/ci.sh
Labels: enhancement

#162 Add integration test
  .github/workflows/ci.yml
  .travis.yml
  Cargo.lock
  Cargo.toml
  ci.sh
  tests/mod.rs
  tests/providers/mod.rs
  tests/providers/tpm.rs
Labels: enhancement
