Repository parallaxsecond/parsec, pull requests merged in 2021-01, with the labels that each got.

#306 Fix lint warning
  Cargo.lock
  src/providers/pkcs11/key_metadata.rs
Labels: code health

#307 Disable Travis builds
  .travis.yml.disabled
Labels: invalid

#316 Add admin configuration
  config.toml
  e2e_tests/tests/per_provider/normal_tests/asym_sign_verify.rs
  src/authenticators/direct_authenticator/mod.rs
  src/authenticators/jwt_svid_authenticator/mod.rs
  src/authenticators/mod.rs
  src/authenticators/unix_peer_credentials_authenticator/mod.rs
  src/key_info_managers/on_disk_manager/mod.rs
  src/utils/service_builder.rs
Labels: enhancement, security

#317 Added support for PsaHashCompute to CryptoAuthLib provider.
  Cargo.lock
  Cargo.toml
  config.toml
  e2e_tests/provider_cfg/all/config.toml
  e2e_tests/provider_cfg/cryptoauthlib/config.toml
  e2e_tests/tests/all_providers/config/tomls/list_providers_1.toml
  e2e_tests/tests/all_providers/config/tomls/list_providers_2.toml
  e2e_tests/tests/all_providers/normal.rs
  src/providers/cryptoauthlib/hash.rs
  src/providers/cryptoauthlib/mod.rs
  src/providers/mod.rs
  src/utils/service_builder.rs
Labels: platforms

#321 Improve mandatory Provide methods
  e2e_tests/tests/all_providers/normal.rs
  e2e_tests/tests/per_provider/normal_tests/hash.rs
  e2e_tests/tests/per_provider/normal_tests/key_agreement.rs
  src/providers/core/mod.rs
  src/providers/mod.rs
Labels: code health

#325 Parsec PsaGenerateRandom operation implementation for CryptoAuthLib provider
  Cargo.toml
  e2e_tests/tests/all_providers/normal.rs
  src/providers/cryptoauthlib/generate_random.rs
  src/providers/cryptoauthlib/mod.rs
Labels: platforms

#324 Add consistency in key creation/deletion
  src/key_info_managers/mod.rs
  src/providers/core/mod.rs
  src/providers/mbed_crypto/key_management.rs
  src/providers/mbed_crypto/mod.rs
  src/providers/mod.rs
  src/providers/pkcs11/key_management.rs
  src/providers/pkcs11/key_metadata.rs
  src/providers/pkcs11/mod.rs
  src/providers/tpm/key_management.rs
  src/providers/tpm/mod.rs
Labels: multitenancy

#328 Remove the spiffe-based authenticator
  Cargo.lock
  Cargo.toml
  ci.sh
  config.toml
  e2e_tests/Cargo.toml
  e2e_tests/provider_cfg/all/Dockerfile
  e2e_tests/provider_cfg/all/config.toml
  src/authenticators/jwt_svid_authenticator/mod.rs
  src/authenticators/mod.rs
  src/utils/service_builder.rs
Labels: bug

#329 Revert "Remove the spiffe-based authenticator"
  Cargo.lock
  Cargo.toml
  ci.sh
  config.toml
  e2e_tests/Cargo.toml
  e2e_tests/provider_cfg/all/Dockerfile
  e2e_tests/provider_cfg/all/config.toml
  src/authenticators/jwt_svid_authenticator/mod.rs
  src/authenticators/mod.rs
  src/utils/service_builder.rs
Labels: bug
