Repository parallaxsecond/parsec, pull requests merged in 2021-02, with the labels that each got.

#333 Parsec PsaHashCompare operation implementation for CryptoAuthLib provider
  e2e_tests/tests/all_providers/normal.rs
  src/providers/cryptoauthlib/hash.rs
  src/providers/cryptoauthlib/mod.rs
Labels: platforms

#343 Create KeyInfoManagerClient
  src/key_info_managers/mod.rs
  src/key_info_managers/on_disk_manager/mod.rs
  src/providers/cryptoauthlib/mod.rs
  src/providers/mbed_crypto/aead.rs
  src/providers/mbed_crypto/asym_encryption.rs
  src/providers/mbed_crypto/asym_sign.rs
  src/providers/mbed_crypto/key_agreement.rs
  src/providers/mbed_crypto/key_management.rs
  src/providers/mbed_crypto/mod.rs
  src/providers/pkcs11/asym_encryption.rs
  src/providers/pkcs11/asym_sign.rs
  src/providers/pkcs11/key_management.rs
  src/providers/pkcs11/key_metadata.rs
  src/providers/pkcs11/mod.rs
  src/providers/tpm/asym_encryption.rs
  src/providers/tpm/asym_sign.rs
  src/providers/tpm/key_management.rs
  src/providers/tpm/mod.rs
  src/providers/tpm/utils.rs
  src/providers/trusted_service/asym_sign.rs
  src/providers/trusted_service/key_management.rs
  src/providers/trusted_service/mod.rs
  src/utils/service_builder.rs
Labels: code health

#347 Add coverage checking in nightly run
  .github/workflows/nightly.yml
  ci.sh
Labels: code health, enhancement

#348 Improve coverage script
  ci.sh
Labels: code health, enhancement
