Repository parallaxsecond/parsec, pull requests merged in 2021-06, with the labels that each got.

#440 Add various tests checking contracts
  Cargo.lock
  Cargo.toml
  e2e_tests/tests/all_providers/normal.rs
  e2e_tests/tests/per_provider/normal_tests/asym_encryption.rs
  e2e_tests/tests/per_provider/normal_tests/asym_sign_verify.rs
  e2e_tests/tests/per_provider/normal_tests/basic.rs
  e2e_tests/tests/per_provider/normal_tests/create_destroy_key.rs
  e2e_tests/tests/per_provider/normal_tests/export_key.rs
  e2e_tests/tests/per_provider/normal_tests/export_public_key.rs
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  src/providers/cryptoauthlib/key_management.rs
  src/providers/pkcs11/key_management.rs
  src/providers/tpm/key_management.rs
Labels: stability

#443 Bump picky crate versions
  e2e_tests/Cargo.toml
  e2e_tests/tests/per_provider/normal_tests/create_destroy_key.rs
  e2e_tests/tests/per_provider/normal_tests/export_key.rs
  e2e_tests/tests/per_provider/normal_tests/export_public_key.rs
  e2e_tests/tests/per_provider/normal_tests/import_key.rs
  src/providers/tpm/utils.rs
Labels: bug

#445 Execute e2e tests with an old version of client
  .github/CODEOWNERS
  Cargo.toml
  ci.sh
  e2e_tests/docker_image/generate-keys.sh
  e2e_tests/docker_image/import-old-e2e-tests.sh
  e2e_tests/docker_image/parsec-service-test-all.Dockerfile
  e2e_tests/tests/per_provider/normal_tests/key_attributes.rs
  src/providers/tpm/utils.rs
Labels: stability

#448 Randomly select the shutdown signal
  .github/CODEOWNERS
  ci.sh
  src/authenticators/direct_authenticator/mod.rs
  src/authenticators/unix_peer_credentials_authenticator/mod.rs
  src/providers/cryptoauthlib/key_slot.rs
Labels: stability

#446 Add ECC functionality to PKCS11 prov
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  e2e_tests/tests/per_provider/normal_tests/asym_sign_verify.rs
  e2e_tests/tests/per_provider/normal_tests/create_destroy_key.rs
  fuzz/Cargo.lock
  src/providers/pkcs11/key_management.rs
  src/providers/pkcs11/utils.rs
  src/providers/tpm/utils.rs
Labels: enhancement

#449 Add a SPIFFE based authenticator
  Cargo.lock
  Cargo.toml
  ci.sh
  config.toml
  e2e_tests/Cargo.toml
  e2e_tests/docker_image/parsec-service-test-all.Dockerfile
  e2e_tests/provider_cfg/all/config.toml
  e2e_tests/tests/per_provider/normal_tests/generate_random.rs
  src/authenticators/jwt_svid_authenticator/mod.rs
  src/authenticators/mod.rs
  src/utils/config.rs
  src/utils/service_builder.rs
  test/cross-compile.sh
Labels: enhancement, multitenancy

#454 Make cross-compilation run on release version
  ci.sh
Labels: bug, testing
