Repository parallaxsecond/parsec, pull requests merged in 2021-07, with the labels that each got.

#452 Add import and export support for ECC for PKCS11
  Cargo.lock
  e2e_tests/tests/all_providers/config/mod.rs
  e2e_tests/tests/all_providers/cross.rs
  e2e_tests/tests/per_provider/normal_tests/asym_sign_verify.rs
  e2e_tests/tests/per_provider/normal_tests/export_key.rs
  e2e_tests/tests/per_provider/normal_tests/export_public_key.rs
  e2e_tests/tests/per_provider/normal_tests/import_key.rs
  src/providers/pkcs11/asym_sign.rs
  src/providers/pkcs11/key_management.rs
  src/providers/pkcs11/utils.rs
Labels: ecosystem, enhancement

#451 Add a way to allow providers to fail instantiation
  Cargo.lock
  Cargo.toml
  config.toml
  e2e_tests/tests/all_providers/config/mod.rs
  e2e_tests/tests/all_providers/config/tomls/no_tpm_support.toml
  src/utils/config.rs
  src/utils/service_builder.rs
Labels: platforms

#473 Add cargo-audit config
  .cargo/audit.toml
Labels: code health, enhancement, security

#474 Adjust TS provider linking
  build.rs
Labels: enhancement, firmware framework

#482 Add TS provider to all-providers
  Cargo.toml
  ci.sh
  e2e_tests/Cargo.toml
  e2e_tests/tests/all_providers/config/mod.rs
  e2e_tests/tests/all_providers/config/tomls/ts_pkcs11_cross.toml
  e2e_tests/tests/all_providers/cross.rs
Labels: enhancement, firmware framework

#483 Add submodule initialisation to CircleCI
  .circleci/config.yml
Labels: bug

#484 Fix CircleCI config format.
  .circleci/config.yml
Labels: bug

#485 Fix git command and use Arm machine
  .circleci/config.yml
Labels: bug

#489 Do not login if no user pin was entered
  config.toml
  e2e_tests/tests/all_providers/config/mod.rs
  e2e_tests/tests/all_providers/config/tomls/no_user_pin.toml
  src/providers/pkcs11/mod.rs
  src/providers/pkcs11/utils.rs
Labels: bug

#490 Modify the git submodule command
  .circleci/config.yml
Labels: bug

#402 Added Option<Slot> to PKCS 11 Provider constructor
  Cargo.lock
  Cargo.toml
  config.toml
  src/providers/pkcs11/mod.rs
  src/utils/config.rs
Labels: enhancement

#494 Remove Mbed Crypto stability linking test
  ci.sh
  e2e_tests/docker_image/parsec-service-test-all.Dockerfile
Labels: invalid, stability

#495 Fix code coverage reports
  Cargo.lock
  README.md
  ci.sh
Labels: bug
