Repository parallaxsecond/parsec, pull requests merged in 2021-05, with the labels that each got.

#414 Create SECURITY.md
  SECURITY.md
Labels: enhancement, security

#415 Fix Contributing link
  README.md
Labels: bug, documentation

#419 Add Codecov and cii badges
  README.md
Labels: documentation

#432 Isolate config logic and add e2e config tests
  .github/CODEOWNERS
  ci.sh
  e2e_tests/src/lib.rs
  e2e_tests/tests/all_providers/config/mod.rs
  e2e_tests/tests/all_providers/config/tomls/various_field_check.toml
  src/authenticators/direct_authenticator/mod.rs
  src/authenticators/mod.rs
  src/authenticators/unix_peer_credentials_authenticator/mod.rs
  src/bin/main.rs
  src/front/listener.rs
  src/key_info_managers/mod.rs
  src/providers/mod.rs
  src/utils/config.rs
  src/utils/mod.rs
  src/utils/service_builder.rs
Labels: stability

#429 Revive the fuzz testing framework
  .github/workflows/ci.yml
  fuzz.sh
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  fuzz/build.rs
  fuzz/docker/Dockerfile
  fuzz/fuzz_targets/fuzz_service.rs
  fuzz/run_fuzz.sh
Labels: security, testing

#433 Fix ServiceConfig import in fuzz_service
  fuzz/fuzz_targets/fuzz_service.rs
Labels: bug

#434 Enable coverage testing for TS provider
  .github/workflows/nightly.yml
  ci.sh
Labels: enhancement

#435 Fix nightly workflow
  .github/workflows/nightly.yml
Labels: bug

#431 [CryptoAuthLib provider] Implementation of psa_export_public_key operation.
  Cargo.lock
  Cargo.toml
  e2e_tests/tests/per_provider/normal_tests/asym_sign_verify.rs
  e2e_tests/tests/per_provider/normal_tests/export_public_key.rs
  src/providers/cryptoauthlib/asym_sign.rs
  src/providers/cryptoauthlib/key_management.rs
  src/providers/cryptoauthlib/key_operations.rs
  src/providers/cryptoauthlib/mod.rs
Labels: platforms

#436 Remove the TS coverage computation
  ci.sh
Labels: bug, testing
