Repository parallaxsecond/parsec, pull requests merged in 2021-03, with the labels that each got.

#352 Fix code coverage docker command
  .github/workflows/nightly.yml
Labels: bug

#353 Run the Codecov script outside container
  .github/workflows/nightly.yml
  ci.sh
Labels: bug

#356 Update docker registry for TPM2 images
  e2e_tests/provider_cfg/all/Dockerfile
  e2e_tests/provider_cfg/tpm/Dockerfile
Labels: bug

#357 Change CI to use published Docker image
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  build.rs
  ci.sh
  e2e_tests/docker_image/Dockerfile
  e2e_tests/docker_image/_exec_wrapper
  e2e_tests/provider_cfg/all/Dockerfile
  e2e_tests/provider_cfg/mbed-crypto/Dockerfile
  e2e_tests/provider_cfg/pkcs11/Dockerfile
  e2e_tests/provider_cfg/tpm/Dockerfile
  e2e_tests/provider_cfg/trusted-service/Dockerfile
Labels: enhancement, testing

#301 Use the new abstraction on the PKCS11 interface
  Cargo.lock
  Cargo.toml
  e2e_tests/tests/per_provider/normal_tests/create_destroy_key.rs
  src/providers/mbed_crypto/aead.rs
  src/providers/mbed_crypto/asym_encryption.rs
  src/providers/mbed_crypto/asym_sign.rs
  src/providers/mbed_crypto/key_agreement.rs
  src/providers/mbed_crypto/key_management.rs
  src/providers/mbed_crypto/mod.rs
  src/providers/pkcs11/asym_encryption.rs
  src/providers/pkcs11/asym_sign.rs
  src/providers/pkcs11/key_management.rs
  src/providers/pkcs11/key_metadata.rs
  src/providers/pkcs11/mod.rs
  src/providers/pkcs11/utils.rs
  src/utils/service_builder.rs
Labels: on-hold, platforms

#361 Enable code coverage for PKCS11, disable for TS
  ci.sh
Labels: code health, testing

#354 Implementation of PsaGenerateKey and PsaDestroyKey operations
  Cargo.lock
  Cargo.toml
  e2e_tests/provider_cfg/all/config.toml
  e2e_tests/tests/all_providers/config/mod.rs
  e2e_tests/tests/all_providers/config/tomls/list_providers_1.toml
  e2e_tests/tests/all_providers/config/tomls/list_providers_2.toml
  e2e_tests/tests/all_providers/normal.rs
  e2e_tests/tests/per_provider/normal_tests/asym_sign_verify.rs
  e2e_tests/tests/per_provider/normal_tests/auth.rs
  e2e_tests/tests/per_provider/normal_tests/create_destroy_key.rs
  e2e_tests/tests/per_provider/normal_tests/export_public_key.rs
  e2e_tests/tests/per_provider/normal_tests/hash.rs
  e2e_tests/tests/per_provider/normal_tests/import_key.rs
  e2e_tests/tests/per_provider/normal_tests/key_attributes.rs
  src/providers/cryptoauthlib/generate_random.rs
  src/providers/cryptoauthlib/hash.rs
  src/providers/cryptoauthlib/key_management.rs
  src/providers/cryptoauthlib/key_operations.rs
  src/providers/cryptoauthlib/key_slot.rs
  src/providers/cryptoauthlib/key_slot_storage.rs
  src/providers/cryptoauthlib/mod.rs
Labels: platforms

#374 Implement a few fixes
  .github/workflows/ci.yml
  config.toml
  e2e_tests/docker_image/Dockerfile
  src/bin/main.rs
  src/providers/trusted_service/context/key_management.rs
Labels: bug, documentation
