Repository parallaxsecond/parsec, pull requests merged in 2021-11, with the labels that each got.

#536 [CryptoAuthLib provider] PsaAeadEncrypt and PsaAeadDecrypt implemented
  Cargo.toml
  e2e_tests/src/lib.rs
  e2e_tests/tests/per_provider/normal_tests/aead.rs
  src/providers/cryptoauthlib/aead.rs
  src/providers/cryptoauthlib/mod.rs
Labels: enhancement

#558 Activate credential
  Cargo.lock
  Cargo.toml
  ci.sh
  config.toml
  e2e_tests/Cargo.toml
  e2e_tests/docker_image/generate-keys.sh
  e2e_tests/provider_cfg/tpm/config.toml
  e2e_tests/src/lib.rs
  e2e_tests/tests/per_provider/normal_tests/key_attestation.rs
  e2e_tests/tests/per_provider/normal_tests/mod.rs
  src/back/backend_handler.rs
  src/providers/mod.rs
  src/providers/tpm/key_attestation.rs
  src/providers/tpm/mod.rs
  src/providers/tpm/utils.rs
  src/utils/config.rs
  src/utils/service_builder.rs
Labels: enhancement

#560 Add ActivateCredential tests and fixes
  e2e_tests/Cargo.toml
  e2e_tests/src/lib.rs
  e2e_tests/tests/all_providers/config/mod.rs
  e2e_tests/tests/all_providers/config/tomls/no_endorsement_auth.toml
  e2e_tests/tests/all_providers/normal.rs
  e2e_tests/tests/per_provider/normal_tests/key_attestation.rs
  src/providers/tpm/key_attestation.rs
  src/providers/tpm/mod.rs
Labels: enhancement

#561 Add clippy and fmt checkt to e2e_tests
  ci.sh
  e2e_tests/src/lib.rs
  e2e_tests/tests/all_providers/config/mod.rs
  e2e_tests/tests/all_providers/cross.rs
  e2e_tests/tests/all_providers/normal.rs
  e2e_tests/tests/per_provider/normal_tests/aead.rs
  e2e_tests/tests/per_provider/normal_tests/asym_encryption.rs
  e2e_tests/tests/per_provider/normal_tests/asym_sign_verify.rs
  e2e_tests/tests/per_provider/normal_tests/auth.rs
  e2e_tests/tests/per_provider/normal_tests/capability_discovery.rs
  e2e_tests/tests/per_provider/normal_tests/create_destroy_key.rs
  e2e_tests/tests/per_provider/normal_tests/export_key.rs
  e2e_tests/tests/per_provider/normal_tests/export_public_key.rs
  e2e_tests/tests/per_provider/normal_tests/import_key.rs
  e2e_tests/tests/per_provider/normal_tests/key_agreement.rs
  e2e_tests/tests/per_provider/normal_tests/key_attributes.rs
  e2e_tests/tests/per_provider/tpm_reset.rs
Labels: code health, testing

#562 Add error handling to ActivateCredential
  e2e_tests/tests/all_providers/config/mod.rs
  e2e_tests/tests/per_provider/normal_tests/key_attestation.rs
  src/providers/tpm/key_attestation.rs
Labels: enhancement, testing
